execute pathogen#infect()

let g:gruvbox_italic=1
set bg=dark
" Wonky in SSH sessions
"set termguicolors
colorscheme gruvbox

" Custom GitGutter commands
command Stage  GitGutterStageHunk
command Revert GitGutterUndoHunk

" Set default encoding to UTF-8
set enc=utf-8

" Set autowrite for use with :make
set autowrite

" Number of visual spaces per TAB
set tabstop=4
" Number of spaces in tab when editing
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab
set backspace=indent,eol,start

"Use terminal title
set title
set titlestring=%F

" Show line numbers
set number
" Keep the cursor 6 lines from bottom of screen.
set scrolloff=6
" Toggle paste mode with f3
set pastetoggle=<F3>

" Allow fuzzy menu
set wildmenu
" Redraw screen lazily
set lazyredraw
"Matching brackets highlighted
set showmatch
" Highlight as characters are entered
set incsearch
" Must be turned off manually
set hlsearch
" Turn off search highlighting with enter
nnoremap <CR> :nohl<CR><CR>

" Use ctrl+[jk] to move lines up and down in normal, insert, and visual mode.
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" enable code folding
set foldenable
set foldlevelstart=15
set foldnestmax=10
set foldmethod=syntax

nnoremap <space> za

" Visual movement
nnoremap j gj
nnoremap k gk

" Force vim to think .md are markdown files on older systems that don't
" have the filetype properly set in /usr/share/vim/vim74/filetype.vim
" (Looking at you $COMPANY dev servers)
autocmd BufNewFile,BufRead *.md set filetype=markdown

" Highlight current line
set cursorline
" Highlight current column
" set cursorcolumn
" Command separated list of columns to highlight
set colorcolumn=100

" Open NERDTree automatically when vim starts up.
" autocmd vimenter * NERDTree
" Open NERDTree automatically when vim starts up empty.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" Toggle NERDTree with Ctrl+n
map <C-n> :NERDTreeToggle<CR>
" Close vim if the only window open is a NERDTree.
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

let g:airline_theme='gruvbox'
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#vimtex#enabled = 1
" Show opened buffers at the top of the screen.
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" Open a new empty buffer. Current buffer must be written.
nmap <C-t> :enew<CR>
" Move to the next buffer.
nmap <C-l> :bnext<CR>
" Move to the previous buffer.
nmap <C-h> :bprevious<CR>

" When creating a new window, make it equal sized to any currently open
" windows. E.g., when using vsplit multiple times.
set equalalways

" Linter settings
let g:ale_fixers = {
\   'python': ['pylint'],
\}

let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1
let g:ale_c_gcc_options = '-std=c11 -Wall -Wextra -Wpedantic'
let g:ale_cpp_gcc_options = '-std=c++17 -Wall -Wextra -Wpedantic'
