#!/bin/bash

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias tree='tree -C'

alias ls='ls -h --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias back="cd -"
alias xo='xdg-open'

alias upd='sudo apt update'
alias upg='sudo apt upgrade'
alias acl='sudo apt-get autoclean'
alias arem='sudo apt-get autoremove'

# :D
alias git-yolo='git commit -am "$(curl -s http://whatthecommit.com/index.txt)"'

alias wiki='vim $VIMWIKI_PATH/index.wiki'
alias todo='vim $VIMWIKI_PATH/todo.wiki'
alias journal='vim $VIMWIKI_PATH/diary/diary.wiki'
alias today='vim -c VimwikiMakeDiaryNote'
alias tomorrow='vim -c VimwikiMakeTomorrowDiaryNote'
alias yesterday='vim -c VimwikiMakeYesterdayDiaryNote'
